require("lua.prototypes.plane")
require("lua.prototypes.autopilot.marker")
require("lua.prototypes.autopilot.tool-path")
require("lua.prototypes.autopilot.tool-config")
require("lua.prototypes.technologies")
